plugins {
    id 'eclipse'
    id 'net.neoforged.moddev' version '2.0.95'
}

version = '1.9.2'
base.archivesName = "loikvy"

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

dependencies {
	implementation files('libs/architectury-13.0.6-neoforge.jar')
    implementation files('libs/uilib-1.0.1-1.21.1-neoforge.jar')
}

tasks.register('restoreProtectedFiles', Copy) {
    from('protected_files/resources/') {
        into('.')
    }
    into 'src/main/resources/'
}

tasks.register('restoreMetaFiles', Copy) {
    from('protected_files/META-INF/') {
        into('.')
    }
    into 'src/main/resources/META-INF/'
}

compileJava.dependsOn 'restoreProtectedFiles', 'restoreMetaFiles'

tasks.named('processResources').configure {
    dependsOn 'restoreProtectedFiles', 'restoreMetaFiles'
}

afterEvaluate {
    tasks.named('createMinecraftArtifacts').configure {
        dependsOn 'restoreProtectedFiles', 'restoreMetaFiles'
    }
}

neoForge {
    version = "21.1.176"

    accessTransformers = [file('src/main/resources/META-INF/accesstransformer.cfg')]

    runs {
        client {
            client()

            def mcreatorJvmOptions = System.getenv('MCREATOR_JVM_OPTIONS')
            if (mcreatorJvmOptions) {
                mcreatorJvmOptions.split("\\s+").findAll { it.trim() }.each { arg ->
                    jvmArgument(arg)
                }
            }
        }
        server {
            server()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        mcreator {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

apply from: 'mcreator.gradle'
