modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="loikvy"
version="1.7.0"
displayName="Loikvy Roleplay"
displayURL="https://github.com/Jemko0"
logoFile="logo.png"
credits="Jemko"
authors="Jemko"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.loikvy]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.176,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.loikvy]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.loikvy]]
    modId="kleidersplayerrenderer"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"



# Start of user code block custom mixins
# End of user code block custom mixins


# Start of user code block dependencies configuration
# End of user code block dependencies configuration